spring.application.name=tower-defense-progress-api
spring.datasource.password=root
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/tower_defense_db
jwt.secret=elenafrumoasamajoctowerdefense1231241403